name: install rye
description: instal rye using in github action
branding:
  icon: download
  color: white
author: phi

runs:
  using: composite
  steps:
    - name: prepare rye
      id: prepare-rye
      shell: bash
      run: |
        RYE_VERSION=$([ "${{ inputs.rye_version }}" = "default" ] && echo "latest" || echo "${{ inputs.rye_version }}")
        RYE_HOME=$([ "${{ inputs.rye_home }}" = "default" ] && echo "" || echo "${{ inputs.rye_home }}")
        PYTHON_VERSION=$([ "${{ inputs.python_version }}" = "default" ] && echo "3.12" || echo "${{ inputs.python_version }}")
        USE_UV=$([ "${{ inputs.use_uv }}" = "default" ] && echo "true" || echo "${{ inputs.use_uv }}")
        RYE_HOME=$([ -z "$RYE_HOME" ] && echo "$HOME/.rye" || echo "$RYE_HOME")
        echo "   rye version: $RYE_VERSION"
        echo "      rye home: $RYE_HOME"
        echo "python version: $PYTHON_VERSION"
        echo "        use uv: $USE_UV"
        echo "rye-version=${RYE_VERSION}" >> $GITHUB_OUTPUT
        echo "rye-home=${RYE_HOME}" >> $GITHUB_OUTPUT
        echo "python-version=${PYTHON_VERSION}" >> $GITHUB_OUTPUT
        echo "use-uv=${USE_UV}" >> $GITHUB_OUTPUT


    - name: install rye
      id: install-rye
      shell: bash
      env:
        RYE_INSTALL_OPTION: '--yes'
        RYE_VERSION: ${{ steps.prepare-rye.outputs.rye-version }}
        RYE_HOME: ${{ steps.prepare-rye.outputs.rye-home }}
      run: |
        curl -sSf https://rye-up.com/get | bash
        echo "${RYE_HOME}/shims" >> $GITHUB_PATH

    - name: setup rye
      id: setup-rye
      shell: bash
      run: |
        rye config --set-bool behavior.use-uv=${{ steps.prepare-rye.outputs.use-uv }}
        rye pin cpython@${{ steps.prepare-rye.outputs.python-version }}

        INSTALLED_RYE_VERSION=$(rye --version | awk '{print $2}' | head -n 1)
        PINNED_PYTHON_VERSION=$(cat .python-version)
        echo "rye-version=${INSTALLED_RYE_VERSION}" >> $GITHUB_OUTPUT
        echo "python-version=${PINNED_PYTHON_VERSION}" >> $GITHUB_OUTPUT

inputs:
  rye_version:
    description: rye version
    default: latest
  rye_home:
    description: Where to install rye
    default: ""
  python_version:
    description: The version of python that rye will use in the workspace
    default: "3.12"
  use_uv:
    description: if 'true', then use uv. else use pip-tools.
    default: 'true'

outputs:
  rye-version:
    description: installed rye version
    value: ${{ steps.setup-rye.outputs.rye-version }}
  rye-home:
    description: installed rye path
    value: ${{ steps.prepare-rye.outputs.rye-home }}
  python-version:
    description: pinned python version
    value: ${{ steps.setup-rye.outputs.python-version }}