name: install rye
description: instal rye using in github action
branding:
  icon: download
  color: white
author: phi

runs:
  using: composite
  steps:
    - name: prepare rye
      id: prepare-rye
      shell: bash
      env:
        INPUT_RYE_VERSION: ${{ inputs.rye-version }}
        INPUT_RYE_HOME: ${{ inputs.rye-home }}
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_USE_UV: ${{ inputs.use-uv }}
      run: $GITHUB_ACTION_PATH/src/action/prepare.sh

    - name: install rye
      id: install-rye
      shell: bash
      env:
        RYE_INSTALL_OPTION: '--yes'
        RYE_VERSION: ${{ steps.prepare-rye.outputs.rye-version }}
        RYE_HOME: ${{ steps.prepare-rye.outputs.rye-home }}
      run: $GITHUB_ACTION_PATH/src/action/install.sh

    - name: setup rye
      id: setup-rye
      shell: bash
      env:
        INPUT_PYTHON_VERSION: ${{ steps.prepare-rye.outputs.python-version }}
        INPUT_USE_UV: ${{ steps.prepare-rye.outputs.use-uv }}
      run: $GITHUB_ACTION_PATH/src/action/setup.sh

inputs:
  rye_version:
    description: rye version
    default: latest
  rye_home:
    description: Where to install rye
    default: ""
  python_version:
    description: The version of python that rye will use in the workspace
    default: "3.12"
  use_uv:
    description: if 'true', then use uv. else use pip-tools.
    default: 'true'

outputs:
  rye-version:
    description: installed rye version
    value: ${{ steps.setup-rye.outputs.rye-version }}
  rye-home:
    description: installed rye path
    value: ${{ steps.prepare-rye.outputs.rye-home }}
  python-version:
    description: pinned python version
    value: ${{ steps.setup-rye.outputs.python-version }}