name: test run

on:
  push:
    branches: [main]
    paths:
      - "**/action.yaml"
      - "**/check.yaml"
      - "src/**/**.sh"

permissions:
  actions: write

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          # default
          - rye_version: "default"
            rye_home: "default"
            python_version: "default"
            use_uv: "default"
            name: "check default"
          # check rye version
          - rye_version: "0.27.0"
            rye_home: "default"
            python_version: "default"
            use_uv: "default"
            name: "check rye version"
          # check rye home
          - rye_version: "default"
            rye_home: "/opt/rye"
            python_version: "default"
            use_uv: "default"
            name: "check rye home"
          # check python version
          - rye_version: "default"
            rye_home: "default"
            python_version: "3.8.15"
            use_uv: "default"
            name: "check python version"
          # check use uv flag
          - rye_version: "default"
            rye_home: "default"
            python_version: "default"
            use_uv: "false"
            name: "check use uv"

    name: "${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v4

      - uses: phi-friday/install-rye@main
        id: install-rye
        name: "${{ matrix.name }}"
        with:
          rye_version: "${{ matrix.rye_version }}"
          rye_home: "${{ matrix.rye_home }}"
          python_version: "${{ matrix.python_version }}"
          use_uv: "${{ matrix.use_uv }}"

      - name: echo stats
        env:
          INPUT_RYE_VERSION: ${{ matrix.rye_version }}
          INPUT_RYE_HOME: ${{ matrix.rye_home }}
          INPUT_PYTHON_VERSION: ${{ matrix.python_version }}
          INPUT_USE_UV: ${{ matrix.use_uv }}
          REAL_RYE_VERSION: "${{ steps.install-rye.outputs.rye-version }}"
          REAL_RYE_HOME: "${{ steps.install-rye.outputs.rye-home }}"
          REAL_PYTHON_VERSION: "${{ steps.install-rye.outputs.python-version }}"
          REAL_USE_UV: "${{ steps.install-rye.outputs.use-uv }}"
        run: ./src/action/check.sh

  prepare-cache:
    runs-on: ubuntu-latest

    steps:
      - id: create-id
        run: |
          UUID=$(uuidgen)
          echo "cache-id=${UUID}" >> $GITHUB_OUTPUT

      - uses: phi-friday/install-rye@main
        id: install-rye
        with:
          rye_home: /opt/rye

      - uses: actions/cache@v4
        with:
          path: /opt/rye
          key: "${{ steps.create-id.outputs.cache-id }}"

    outputs:
      cache-id: "${{ steps.create-id.outputs.cache-id }}"

  cache:
    runs-on: ubuntu-latest
    needs: prepare-cache

    steps:
      - uses: actions/cache@v4
        id: get-cache
        with:
          path: /opt/rye
          key: "${{ needs.prepare-cache.outputs.cache-id }}"

      - name: check cache hit(false)
        if: steps.get-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: add path
        if: steps.get-cache.outputs.cache-hit == 'true'
        run: echo "/opt/rye/shims" >> $GITHUB_PATH

      - name: run rye
        run: rye --version

  remove-cache:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - prepare-cache
      - cache
    steps:
      - name: remove cache
        id: remove-cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh cache delete "${{ needs.prepare-cache.outputs.cache-id }}" --repo phi-friday/install-rye
