name: test run

on:
  push:
    branches: [main]
    paths:
      - "**/action.yaml"
      - "**/check.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: phi-friday/install-rye@main
        id: install-rye

      - name: echo stats
        run: |
          echo "   rye version: ${{ steps.install-rye.outputs.rye-version }}"
          echo "      rye home: ${{ steps.install-rye.outputs.rye-home }}"
          echo "python version: ${{ steps.install-rye.outputs.python-version }}"
          echo "        use uv: $(rye config --get behavior.use-uv)"

  check-other-rye:
    runs-on: ubuntu-latest
    steps:
      - uses: phi-friday/install-rye@main
        id: install-rye
        with:
          rye_version: 0.27.0

      - name: echo stats
        run: |
          echo "   rye version: ${{ steps.install-rye.outputs.rye-version }}"
          echo "      rye home: ${{ steps.install-rye.outputs.rye-home }}"
          echo "python version: ${{ steps.install-rye.outputs.python-version }}"
          echo "        use uv: $(rye config --get behavior.use-uv)"
          if [[ "${{ steps.install-rye.outputs.rye-version }}" != "0.27.0" ]]; then exit 1 fi


  check-other-path:
    runs-on: ubuntu-latest
    steps:
      - uses: phi-friday/install-rye@main
        id: install-rye
        with:
          rye_home: /opt/rye

      - name: echo stats
        run: |
          echo "   rye version: ${{ steps.install-rye.outputs.rye-version }}"
          echo "      rye home: ${{ steps.install-rye.outputs.rye-home }}"
          echo "python version: ${{ steps.install-rye.outputs.python-version }}"
          echo "        use uv: $(rye config --get behavior.use-uv)"
          if [[ "${{ steps.install-rye.outputs.rye-home }}" != "/opt/rye" ]]; then exit 1 fi


  check-without-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: phi-friday/install-rye@main
        id: install-rye
        with:
          use_uv: false

      - name: echo stats
        run: |
          echo "   rye version: ${{ steps.install-rye.outputs.rye-version }}"
          echo "      rye home: ${{ steps.install-rye.outputs.rye-home }}"
          echo "python version: ${{ steps.install-rye.outputs.python-version }}"
          echo "        use uv: $(rye config --get behavior.use-uv)"
          if [[ "$(rye config --get behavior.use-uv)" != "false" ]]; then exit 1 fi