name: test in windows

on:
  push:
    branches: [main]
    paths:
      - "action.yaml"
      - ".github/workflows/windows.yaml"

jobs:
  check:
    runs-on: windows-latest

    steps:

      - shell: bash
        run: echo $OSTYPE

  check2:
    runs-on: ubuntu-latest

    steps:

      - shell: bash
        run: echo $OSTYPE